version: '3.5'
services:
  dev:
    user: root
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/usr/src/{{cookiecutter.project_slug}}
    container_name: {{cookiecutter.package_name}}_dev
    working_dir: /usr/src/{{cookiecutter.project_slug}}
    env_file:
      - docker.env
